name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.4.21255.9
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore ./src/Loon.sln
    - name: Build
      run: dotnet build ./src/Loon.sln -c Release --no-restore
